title: Catalunya en dades
name: DATACAT
description: > # this means to ignore newlines until "baseurl:"
  Periodisme de dades. La veritat és tossuda. Nosaltres també.
permalink: ':title/'
#baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: joethebrew
# Author Settings
author: DATACAT # add your name
author-img: datacat.png # add your photo
about-author: Periodisme de dades
social-twitter: joethebrew
social-facebook: # add your Facebook handle
social-github: datacatdata # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: joe@datacat.cc

# Disqus
discus-identifier: #mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
